services:
  consul:
    container_name: universe-simulator-consul
    image: consul:1.12.2
    restart: always
    command: agent
    ports:
      - 8500:8500
    volumes:
      - consul:/consul/data
      - ./consul.json:/consul/config/consul.json

  rabbitmq:
    container_name: universe-simulator-rabbitmq
    image: rabbitmq:3.10.5-management
    restart: always
    hostname: universe-simulator
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  elasticsearch:
    container_name: universe-simulator-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 2gb
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  kibana:
    container_name: universe-simulator-kibana
    image: docker.elastic.co/kibana/kibana:8.2.2
    restart: always
    ports:
      - 5601:5601

  logstash:
    container_name: universe-simulator-logstash
    image: docker.elastic.co/logstash/logstash:8.2.2
    restart: always
    ports:
      - 4560:4560
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

volumes:
  consul:
  rabbitmq:
  elasticsearch:
