services:
  consul:
    image: consul:1.12.0
    container_name: universe-simulator-consul
    restart: always
    command: agent
    ports:
      - 8500:8500
    volumes:
      - consul:/consul/data
      - ./consul.json:/consul/config/consul.json

  rabbitmq:
    image: rabbitmq:3.10.2-management
    container_name: universe-simulator-rabbitmq
    restart: always
    hostname: universe-simulator
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.1
    container_name: universe-simulator-elasticsearch
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1gb
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.1
    container_name: universe-simulator-kibana
    restart: always
    ports:
      - 5601:5601

  logstash:
    image: docker.elastic.co/logstash/logstash:8.2.1
    container_name: universe-simulator-logstash
    restart: always
    ports:
      - 4560:4560
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  zipkin:
    image: openzipkin/zipkin:2.23.16
    container_name: universe-simulator-zipkin
    restart: always
    environment:
      - RABBIT_ADDRESSES=rabbitmq:5672
      - RABBIT_USER=user
      - RABBIT_PASSWORD=password
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch:9200
      - ES_TEMPLATE_PRIORITY=1
      - ES_INDEX_SHARDS=1
      - ES_INDEX_REPLICAS=0
    ports:
      - 9411:9411

volumes:
  consul:
  rabbitmq:
  elasticsearch:
