services:
  vault:
    image: vault:1.9.2
    container_name: universe-simulator-vault
    restart: always
    cap_add:
      - IPC_LOCK
    command: server
    ports:
      - 8200:8200
    volumes:
      - vault-file:/vault/file
      - vault-logs:/vault/logs
      - ./vault.json:/vault/config/vault.json
      - ~/universe-simulator/universe-simulator-cert.pem:/vault/file/universe-simulator-cert.pem
      - ~/universe-simulator/universe-simulator-key.pem:/vault/file/universe-simulator-key.pem

  rabbitmq:
    image: rabbitmq:3.9.11-management
    container_name: universe-simulator-rabbitmq
    restart: always
    hostname: universe-simulator
    ports:
      - 5671:5671
      - 15671:15671
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ~/universe-simulator/universe-simulator-cert.pem:/var/lib/rabbitmq/universe-simulator-cert.pem
      - ~/universe-simulator/universe-simulator-key.pem:/var/lib/rabbitmq/universe-simulator-key.pem

  zipkin:
    image: openzipkin/zipkin:2.23.16
    container_name: universe-simulator-zipkin
    restart: always
    environment:
      - RABBIT_ADDRESSES=rabbitmq:5671
      - RABBIT_USER=user
      - RABBIT_PASSWORD=password
      - RABBIT_USE_SSL=true
    ports:
      - 9411:9411

volumes:
  vault-file:
  vault-logs:
  rabbitmq:
