services:
  consul:
    image: consul:1.11.3
    container_name: universe-simulator-consul
    restart: always
    command: agent
    ports:
      - 8500:8500
    volumes:
      - consul:/consul/data
      - ./consul.json:/consul/config/consul.json
      - ~/universe-simulator/universe-simulator-cert.pem:/consul/data/universe-simulator-cert.pem
      - ~/universe-simulator/universe-simulator-key.pem:/consul/data/universe-simulator-key.pem

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: universe-simulator-elasticsearch
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: universe-simulator-kibana
    restart: always
    ports:
      - 5601:5601

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.0
    container_name: universe-simulator-logstash
    restart: always
    ports:
      - 4560:4560
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  rabbitmq:
    image: rabbitmq:3.9.13-management
    container_name: universe-simulator-rabbitmq
    restart: always
    hostname: universe-simulator
    ports:
      - 5671:5671
      - 15671:15671
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ~/universe-simulator/universe-simulator-cert.pem:/var/lib/rabbitmq/universe-simulator-cert.pem
      - ~/universe-simulator/universe-simulator-key.pem:/var/lib/rabbitmq/universe-simulator-key.pem

  zipkin:
    image: openzipkin/zipkin:2.23.16
    container_name: universe-simulator-zipkin
    restart: always
    environment:
      - RABBIT_ADDRESSES=rabbitmq:5671
      - RABBIT_USER=user
      - RABBIT_PASSWORD=chromecomplainedsohereitis123
      - RABBIT_USE_SSL=true
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch:9200
      - ES_TEMPLATE_PRIORITY=1
      - ES_INDEX_SHARDS=1
      - ES_INDEX_REPLICAS=0
    ports:
      - 9411:9411

volumes:
  consul:
  elasticsearch:
  rabbitmq:
