= Project description

Library with common code for use in other projects.

#This file contains documentation which is common across all projects.#

== Language
`Java 17`

== Build tool
`Gradle Wrapper`

=== Config
Gradle wrapper properties can be found in the `gradle/wrapper/gradle-wrapper.properties` file.

=== Updating
You can update gradle wrapper with: `./gradlew wrapper --gradle-version=x.x.x --distribution-type=all
--gradle-distribution-sha256-sum=some-checksome`. Valid gradle distribution checksomes can be found at
gradle's https://gradle.org/release-checksums/[Checksome reference page].

== Framework
`Spring Boot`

=== Profiles
You can have as many spring boot profiles as needed. Profiles usually map to environments (dev,
staging, prod). If you need to override some properties for an environment, add a new
`bootstrap-xxx.properties` or `application-xxx.properties` file, where xxx is the name of your
profile. Keep in mind that the `test` profile is reserved for testing purposes and the `local` profile
for local development. `bootstrap-local.properties` and `application-local.properties` files are
excluded from git.

== Testing

=== Unit tests
`JUnit 5` `Mockito` `AssertJ`

=== Integration tests
`Testcontainers`

=== Code coverage
`JaCoCo` plugin is used to analyze code coverage.

==== Report
You can generate the test coverage report with: `./gradlew jacocoTestReport`. The report can be viewed
by opening the `build/reports/jacoco/test/html/index.html` file.

==== Exclusions
Classes which are excluded from jacoco reports are described in the `jacocoExclusions` method in
`build.gradle`. Additionally, all lombok generated code is also excluded. This is achieved with the
`lombok.addLombokGeneratedAnnotation = true` parameter in the `lombok.config` file. If this parameter
is present, lombok will annotate all generated code with its `@Generated` annotation and jacoco
automatically excludes such code from processing.

==== Rules
100% code coverage is enforced by the `jacocoTestCoverageVerification` task. You can run this task
with: `./gradlew jacocoTestCoverageVerification`. If the coverage falls below 100%, the task will
fail.

== CI/CD
`Github Actions` is used for CI/CD automation. The workflow file can be found in the
`.github/workflows` directory.

=== Steps
* Check out code from the repository
* Install java
* Validate `gradle-wrapper.jar`
* Build, test and check code coverage
* _In case of common library:_ Publish a package to `GitHub Packages` with gradle's `publish` task.
You need to add github packages url to your repository secrets.
* _In case of other projects:_ Build a docker image with gradle's `bootBuildImage` task and upload to
`Docker Hub`. You need to add docker registry credentials to your repository secrets.

== Secrets & configuration
`Hashicorp Vault` is used to store secrets and other variable configuration. If you stop or restart
vault container, vault gets sealed, and you'll need to unseal it to be able to use it again.

== HTTPS/TLS
All services run on `HTTPS/TLS`. Additionally, `HTTP/2` protocol is also enabled.

== Messaging
`RabbitMQ`

== Distributed tracing
`Sleuth` `Zipkin`
