= Project description

Library with common code for use in other projects.

== Language
The project is built with `Java 11`.

== Build tool
`Gradle Wrapper` is used as a build tool for the project. Gradle-related properties can be found in
the `gradle/wrapper/gradle-wrapper.properties` file.

=== Updating
You can update gradle wrapper with: `./gradlew wrapper --gradle-version=x.x.x --distribution-type=all
--gradle-distribution-sha256-sum=some-checksome`. Valid gradle distribution checksomes can be found
at gradle's https://gradle.org/release-checksums/[Checksome reference page].

== Code coverage
`JaCoCo` plugin is used to analyze code coverage.

=== Report
You can generate the test coverage report with: `./gradlew jacocoTestReport`. The report can be
viewed by opening the `build/reports/jacoco/test/html/index.html` file.

=== Exclusions
Classes which are excluded from jacoco reports are described in the `jacocoExclusions` method in
`build.gradle`. Additionally, all lombok generated code is also excluded. This is achieved with the
`lombok.addLombokGeneratedAnnotation = true` parameter in the `lombok.config` file. If this parameter
is present, lombok will annotate all generated code with its `@Generated` annotation and jacoco
automatically excludes such code from processing.

=== Rules
100% code coverage is enforced by the `jacocoTestCoverageVerification` task. You can run this task
with: `./gradlew jacocoTestCoverageVerification`. If the coverage falls below 100%, the task will
fail.

== CI/CD
`Github Actions` is used for automating the project workflow. The workflow file can be found in the
`.github/workflows` directory.

=== Steps
* Check out code from the repository
* Install java
* Validate `gradle-wrapper.jar`
* Build, test and check code coverage
* Publish a package to `GitHub Packages` with gradle's `publish` task. You need to add github packages
url to your repository secrets.
