= Project setup

#This file contains documentation which is common for all projects.#

== Https/TLS
You need to have the following files in your `~/universe-simulator` directory:

* a keystore file named `universe-simulator.p12`
* a certificate file named `universe-simulator-cert.pem`
* a private key file named `universe-simulator-key.pem`

=== Keystore
The certificate in the keystore can be either self-signed or provided by a CA. You can use `openssl`
and java's `keytool` utility for working with keystore. To create all the necessary files, follow
these steps:

* Create a keystore with a self-signed certificate and a private key: `keytool -genkeypair -v -alias
universe-simulator -keystore universe-simulator.p12 -keyalg RSA -validity 365 -ext
SAN=dns:localhost,ip:127.0.0.1`. #Make sure to enter some valid country code when prompted.#

* Extract the certificate from the keystore with:
`openssl pkcs12 -in universe-simulator.p12 -out universe-simulator-cert.pem -nokeys`

* Extract the private key from the keystore with:
`openssl pkcs12 -in universe-simulator.p12 -out universe-simulator-key.pem -nodes -nocerts`

* Add the certificate to your java truststore:
`keytool -importcert -v -cacerts -alias universe-simulator -file universe-simulator-cert.pem`

* Add the certificate to your browser's (or OS) trusted certificate list.

== Software
Go to the `development` directory (in the `common` project and in other projects where it exists) and
run `docker-compose -p universe-simulator up -d` to install all required software components.

== Configuration

=== Environment variables
Add the following OS environment variables:

* `US_GITHUB_PACKAGES_USER`
* `US_GITHUB_PACKAGES_TOKEN`

=== Properties
Create a `application-local.properties` file next to `application.properties` in all projects except
`config-server` and add the following properties:

* `spring.config.import=configserver:https://localhost:8888`
* `server.port`

== Running an application
You can run an application with the `local` profile from your IDE or with the following command:
`./gradlew bootRun --args='--spring.profiles.active=local'`.
