on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'com.example.universe.simulator.common'
          package-type: 'maven'
          min-versions-to-keep: 1
