on:
  schedule:
    - cron: '40 03 * * *'

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: dependencyCheckAnalyze --build-cache --info --stacktrace --warning-mode all
