on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      checkout code
      - uses: actions/checkout@v2
#      install java
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
#      validate gradle wrapper
      - uses: gradle/wrapper-validation-action@v1
#      build, test and code coverage
      - uses: burrunan/gradle-cache-action@v1
        with:
          arguments: build jacocoTestCoverageVerification --info --stacktrace
#      publish package
      - uses: burrunan/gradle-cache-action@v1
#        if: github.ref == 'refs/heads/master'
        with:
          arguments: publish --info --stacktrace
        env:
          US_GITHUB_PACKAGES_URL: ${{ secrets.US_GITHUB_PACKAGES_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
