on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      checkout code
      - uses: actions/checkout@v2
#      install java
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
#      validate gradle wrapper
      - uses: gradle/wrapper-validation-action@v1
#      build, test and code coverage
      - uses: burrunan/gradle-cache-action@v1
        with:
          arguments: build jacocoTestCoverageVerification --info --stacktrace
