on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew build --build-cache --info --stacktrace
      - run: ./gradlew sonarqube --build-cache --info --stacktrace
        env:
          US_SONARQUBE_TOKEN: ${{ secrets.US_SONARQUBE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        with:
          scanMetadataReportFile: build/sonar/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.US_SONARQUBE_TOKEN }}
      - name: publish
        if: github.ref == 'refs/heads/main'
        run: ./gradlew publish --build-cache --info --stacktrace
        env:
          US_GITHUB_PACKAGES_USER: ${{ secrets.US_GITHUB_PACKAGES_USER }}
          US_GITHUB_PACKAGES_TOKEN: ${{ secrets.US_GITHUB_PACKAGES_TOKEN }}
